version: '3'

services:
  server:
    image: nginx:1.19-alpine
    container_name: nginx_server
    restart: always
    ports:
      - 80:80
      # - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/www
